version: '3'

services:
  stocks:
    build: ./stocks
    restart: always # always restart the container
    volumes:
      - type: bind
        source: ./stocks # host directory
        target: /stocks # container directory
    environment:
      - MONGO_DB_NAME=stocks
    ports:
      - "5001:8000"  # Map to external port 5001
    expose:
      - 8000
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  capitalgains:
    build: ./capital-gains # path is relative to docker-compose-shorthand.yml location
    restart: always # always restart the container
    volumes:
      - type: bind
        source: ./capital-gains # host directory
        target: /capital-gains # container directory
    environment:
      - FLASK_RUN_PORT=8080
    ports:
      - "5003:8080" # host:container
    expose:
      - 8080
    depends_on:
      - "stocks"
