name: Build and push Docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set DATE
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          cd stocks
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/stocks
          docker tag ${{ secrets.DOCKER_USERNAME }}/stocks ${{ secrets.DOCKER_USERNAME }}/stocks:${{ env.DATE }}
          cd ../capital-gains
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/capital-gains
          docker tag ${{ secrets.DOCKER_USERNAME }}/stocks ${{ secrets.DOCKER_USERNAME }}/capital-gains:${{ env.DATE }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/stocks
          docker push ${{ secrets.DOCKER_USERNAME }}/stocks:${{ env.DATE }}
          docker push ${{ secrets.DOCKER_USERNAME }}/capital-gains
          docker push ${{ secrets.DOCKER_USERNAME }}/capital-gains:${{ env.DATE }}
  tests:
    runs-on: ubuntu-latest

    services:
      stocks-service:
        image: itayboros/stocks
        ports:
          - 5001:8000

      capital-gains-service:
        image: itayboros/capital-gains
        ports:
          - 5003:8000

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest requests

      - name: Log start time and setup log file
        run: |
          echo "$(date -Iminutes)" > log.txt
          echo "Submitters: Your Name Here" >> log.txt
          echo "Initializing log file..." >> log.txt

      - name: Wait for services to start
        run: |
          sleep 10
          echo "Container up and running" >> log.txt || echo "Container failed to run" >> log.txt

      - name: Run tests and capture results
        run: |
          pytest tests/assn4_test.py -v > test-results.txt || echo "tests failed" >> log.txt
          echo "tests succeeded" >> log.txt

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: log.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results.txt
