name: Build and push Docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set DATE
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          cd stocks
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/stocks
          docker tag ${{ secrets.DOCKER_USERNAME }}/stocks ${{ secrets.DOCKER_USERNAME }}/stocks:${{ env.DATE }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/stocks
          docker push ${{ secrets.DOCKER_USERNAME }}/stocks:${{ env.DATE }}
