name: Python Tests with Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-python:
    runs-on: ubuntu-latest

    services:
      stocks-service:
        image: ${{ secrets.DOCKER_USERNAME }}/stocks
        ports:
          - 5001:8000

      capital-gains-service:
        image: ${{ secrets.DOCKER_USERNAME }}/capital-gains
        ports:
          - 5003:8000

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest requests

      - name: Log start time and setup log file
        run: |
          echo "$(date -Iminutes)" > log.txt
          echo "Submitters: Your Name Here" >> log.txt
          echo "Initializing log file..." >> log.txt

      - name: Wait for services to start
        run: |
          sleep 10
          echo "Container up and running" >> log.txt || echo "Container failed to run" >> log.txt

      - name: Run tests and capture results
        run: |
          pytest project4v2/tests/assn4_test.py -v > test-results.txt || echo "tests failed" >> log.txt
          echo "tests succeeded" >> log.txt

      - name: Generate query result file
        run: |
          curl "http://localhost:5001/query?param=value" > query-results.txt

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: log.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results.txt

      - name: Upload query results
        uses: actions/upload-artifact@v4
        with:
          name: query-results
          path: query-results.txt
